=== QueenZahra95/divachain/src/schema/block/block.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "/schema/block/block.json",

  "type": "object",
  "properties": {
    "v": {
      "type": "integer",
      "minimum": 1
    },
    "ph": {
      "type": "string",
      "pattern": "^[A-Za-z0-9_-]{43}$"
    },
    "h": {
      "type": "string",
      "pattern": "^[A-Za-z0-9_-]{43}$"
    },
    "tx": {
      "type": "array",
      "items": {
        "$ref": "transaction/tx.json"
      },
      "minItems": 1,
      "uniqueItems": true
    },
    "hght": {
      "type": "integer",
      "minimum": 1
    },
    "vts": {
      "type": "array",
      "items": {
        "$ref": "votes.json"
      },
      "uniqueItems": true
    }
  },
  "required": [
    "v",
    "ph",
    "h",
    "tx",
    "hght",
    "vts"
  ],
  "additionalProperties": false
}

=== QueenZahra95/divachain/genesis/block.json
{
  "v": 1,
  "ph": "0000000000000000000000000000000000000000000",
  "h": "0000000000000000000000000000000000000000000",
  "tx": [
    {
      "ident": "genesis",
      "orgn": "0000000000000000000000000000000000000000000",
      "ts": 88355100000,
      "cmds": [
        {
          "seq": 1,
          "cmd": "addPeer",
          "host": "127.27.26.201",
          "port": 17468,
          "pk": "Zfef2MB4o2-YMn5_99AdCU0tNmfLehtPvmlaOd1VMd4"
        },
        {
          "seq": 2,
          "cmd": "modifyStake",
          "pk": "Zfef2MB4o2-YMn5_99AdCU0tNmfLehtPvmlaOd1VMd4",
          "stake": 1000
        },
        {
          "seq": 3,
          "cmd": "addPeer",
          "host": "127.27.26.202",
          "port": 17468,
          "pk": "41wPScPyIefJubclRIXGTqR-rPw5Bkk9AZ_Vscisa0M"
        },
        {
          "seq": 4,
          "cmd": "modifyStake",
          "pk": "41wPScPyIefJubclRIXGTqR-rPw5Bkk9AZ_Vscisa0M",
          "stake": 1000
        },
        {
          "seq": 5,
          "cmd": "addPeer",
          "host": "127.27.26.203",
          "port": 17468,
          "pk": "jDt5CNNoZvFw2dyskjC8foMEEHsDjXqRVjv8KUU1THg"
        },
        {
          "seq": 6,
          "cmd": "modifyStake",
          "pk": "jDt5CNNoZvFw2dyskjC8foMEEHsDjXqRVjv8KUU1THg",
          "stake": 1000
        },
        {
          "seq": 7,
          "cmd": "addPeer",
          "host": "127.27.26.204",
          "port": 17468,
          "pk": "ZOzTir2BDHnUm4ZscJJozE5FFhQDJ8mMAgEsn5kYIqg"
        },
        {
          "seq": 8,
          "cmd": "modifyStake",
          "pk": "ZOzTir2BDHnUm4ZscJJozE5FFhQDJ8mMAgEsn5kYIqg",
          "stake": 1000
        },
        {
          "seq": 9,
          "cmd": "addPeer",
          "host": "127.27.26.205",
          "port": 17468,
          "pk": "YWG64iZFX0btUDV6FoW4APBb81h4fSRFUtBt4hmErH0"
        },
        {
          "seq": 10,
          "cmd": "modifyStake",
          "pk": "YWG64iZFX0btUDV6FoW4APBb81h4fSRFUtBt4hmErH0",
          "stake": 1000
        },
        {
          "seq": 11,
          "cmd": "addPeer",
          "host": "127.27.26.206",
          "port": 17468,
          "pk": "9Hn3TIO-dfVnxNH3YcD1-0eCCVCJxUhypSOhO8vV-ko"
        },
        {
          "seq": 12,
          "cmd": "modifyStake",
          "pk": "9Hn3TIO-dfVnxNH3YcD1-0eCCVCJxUhypSOhO8vV-ko",
          "stake": 1000
        },
        {
          "seq": 13,
          "cmd": "addPeer",
          "host": "127.27.26.207",
          "port": 17468,
          "pk": "-KvoXDm7WXT40pBq32kTeC-p8zyQZm2nlv_SVM2ZiA0"
        },
        {
          "seq": 14,
          "cmd": "modifyStake",
          "pk": "-KvoXDm7WXT40pBq32kTeC-p8zyQZm2nlv_SVM2ZiA0",
          "stake": 1000
        }
      ],
      "sig": "00000000000000000000000000000000000000000000000000000000000000000000000000000000000000"
    }
  ],
  "hght": 1,
  "vts": []
}
